version: '3'
services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    networks: 
      - desafio-node
    volumes: 
      - ./mysql:/var/lib/mysql 
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=node
      - MYSQL_PASSWORD=node
  app:
    build:
      context: ./nodejs
      dockerfile: Dockerfile    
    container_name: app
    networks: 
      - desafio-node
    tty: true
    volumes: 
      - ./nodejs/src:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && dockerize -wait tcp://db:3306 && node index.js"
    restart: always
    depends_on: 
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks: 
      - desafio-node
    ports: 
      - "8080:80"
    depends_on: 
      - db
      - app
networks: 
  desafio-node:
    driver: bridge